### PR TITLE
Add simple query string query

### PR DESCRIPTION
**Pull request by HeroicEric**
Adds support for the [simple query string query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html)

### CODE REVIEW

**Comment by HeroicEric** [comment]
I'm not sure if there's a simpler/more direct way of testing a Virtus attribute

**Comment by HeroicEric** [comment]
Would you mind also releasing a new version?

**Comment by cschuch** [comment]
@HeroicEric - thanks! Sorry it took me a while, I was on vacation this week and forgot to release a new version with your last PR. I just pushed 0.0.17 as a release on github and on rubygems.

**Comment by HeroicEric** [comment]
@cschuch thanks!

**Pull request merged**
